### ISSUE TITLE
Measuring performance issues

### ISSUE THREAD

**Issue by fcole90** [mauro-idsia/blip#9]
Hi,
I am trying to measure the running time of blip but in my experiments it seems like that if I put a very high time constraint (is it possible to not set one?) , the algorithm runs until the end of such constraint, regardless of the tree-width boundary imposed.

E.g. Using the following parameters:
`java -jar blip.jar solver.kmax -j data/child-5000.jkl -r data/child-5000.kmax.res -t 9999 -b 0 -w 1 -v 1`

Is this expected or should it terminate early instead?

What I am trying to do is to measure how the algorithm scales as the number of features and samples rises. Do you think it would be feasible?

Best regards,
Fabio

**Comment by mauro-idsia** [comment]
This is the expected behaviour of the algorithm - these are approximate methods, that iteratively sample new candidate solution using all the available time. 

Measurement in this area is tricky, since one would need the optimal solution in order to do that, and the exact approaches to bounded-treewidth structure learning can handle at most dozens of variables.

**Comment by fcole90** [comment]
OK, thanks for pointing this out. So the comparison is done using constant time (60 secs) and comparing the W score among the different algorithms, right?

**Comment by mauro-idsia** [comment]
That is a possible way (but not necessarily the only one).
